
<?php

/**
 * @var $this Local_Manadev_Block_Support_TicketForm
 */
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo Mage::helper('local_manadev')->__('Open Support Ticket') ?></h1>
</div>
<form action="<?php echo $this->getFormAction(); ?>" id="ticketForm" class="m-form" method="post" enctype="multipart/form-data">
    <div class="fieldset">
        <ul class="form-list">
            <li class="fields">
                <h2 class="legend"><?php echo Mage::helper('local_manadev')->__('Product Information') ?></h2>
                <div class="field"><strong>Name: </strong><?php echo $this->getCustomerName(); ?></div>
                <div class="field"><strong>E-mail: </strong><?php echo $this->getEmail(); ?></div>
                <div class="field"><strong>Order #: </strong><?php echo $this->getOrderNo(); ?></div>
                <div class="field"><strong>Product: </strong><?php echo $this->getProductName(); ?></div>
                <div class="field"><strong>Support Valid Until: </strong><?php echo $this->getSupportValidTil(); ?></div>
                <div class="field"><strong>Registered URL: </strong><?php echo $this->getRegisteredURL(); ?></div>
            </li>

            <li class="fields">
                <div class="field">
                    <label for="contact_email" class="required"><strong><?php echo Mage::helper('local_manadev')->__('Contact Email') ?><em>*</em></strong></label>
                    <div class="input-box">
                        <input name="contact_email" id="contact_email" class="input-text required-entry validate-email" type="text" value="<?php echo $this->getEmail()?>"/>
                        <p class="note">We will reply to you in this email.</p>
                    </div>
                </div>
            </li>


            <li class="fields">
                <label for="issue_details" class="required"><strong><?php echo Mage::helper('local_manadev')->__('Issue Details') ?><em>*</em></strong></label>
                <div class="input-box">
                    <textarea rows="10" cols="100" name="issue_details" class="input-text required-entry"><?php echo $this->getIssueDetails()?></textarea>
                    <blockquote class="m-lightgrey">
                        <p>Please provide the following information on the Issue Details:</p>
                        <ul class="features">
                            <li>Direct link to page having the issue and specify exact steps on how to reproduce the issue.</li>
                            <li>If site is protected by .htaccess or other means, please provide corresponding credentials.</li>
                            <li>If you think that we need detailed examination on the server, please provide Magento Admin Panel and SFTP credentials.</li>
                        </ul>
                    </blockquote>
                </div>
            </li>

            <li class="fields">
                <div class="field attachments">
                    <div class="space"></div>
                    <label for="screenshot_1"><strong><?php echo Mage::helper('contacts')->__('Screenshot 1') ?></strong> (JPG, PNG, or GIF)</label>
                    <div class="input-box">
                        <input name="screenshot_1" id="screenshot_1" class="input-text" type="file" accept="image/png, image/jpeg, image/gif"/>
                    </div>
                    <label for="screenshot_2"><strong><?php echo Mage::helper('contacts')->__('Screenshot 2') ?></strong> (JPG, PNG, or GIF)</label>
                    <div class="input-box">
                        <input name="screenshot_2" id="screenshot_2" class="input-text" type="file" accept="image/png, image/jpeg, image/gif"/>
                    </div>
                    <label for="screenshot_3"><strong><?php echo Mage::helper('contacts')->__('Screenshot 3') ?></strong> (JPG, PNG, or GIF)</label>
                    <div class="input-box">
                        <input name="screenshot_3" id="screenshot_3" class="input-text" type="file" accept="image/png, image/jpeg, image/gif"/>
                    </div>
                </div>
            </li>

        </ul>
    </div>

    <div class="buttons-set">
        <button type="submit" title="<?php echo Mage::helper('local_manadev')->__('Submit Support Ticket') ?>" class="button"><span><span><?php echo Mage::helper('local_manadev')->__('Submit Support Ticket') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var contactForm = new VarienForm('ticketForm', true);
    //]]>
</script>