<?php
/**
 * @category    Mana
 * @package     ManaPro_Video
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $_images = $this->getGalleryImages();
    $_videos = $this->getVideos();
    $_baseVideo = Mage::helper('manapro_video')->getBaseVideo($_videos);
    $_visibleVideos = Mage::helper('manapro_video')->getVisibleVideos($_videos);
    $_display = Mage::getStoreConfig('manapro_video/display/media');
?>
<?php if($_baseVideo) : ?>
<p class="product-image"><?php echo $this->getVideoHtml($_baseVideo, array('width' => 265, 'height' => 265, 'border' => 0)) ?></p>
<?php else : ?>
<p class="product-image">
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<?php endif; ?>
<?php if (count($_images) || count($_visibleVideos)): ?>
<?php if ($_display == 'tabs'): ?>
<div class="more-views" id="m-video-tabs">
    <ul class="m-tabs">
        <?php if (count($_images)): ?><li><a href="#m-image-tab"><?php echo $this->__('Images') ?></a></li><?php endif; ?>
        <?php if (count($_visibleVideos)): ?><li><a href="#m-video-tab"><?php echo $this->__('Videos') ?></a></li><?php endif; ?>
    </ul>
    <ul>
    <?php if (count($_visibleVideos)): ?>
    <div id="m-video-tab">
        <ul>
            <?php foreach ($_visibleVideos as $_video): ?>
            <li>
                <a href="#" class="m-video-thumbnail" id="m-video-<?php echo $_video->getId() ?>" title="<?php echo $this->htmlEscape($_video->getLabel()) ?>">
                    <img src="<?php echo $this->helper('manapro_video')->getVideoImage($_video, 'thumbnail', 56) ?>"
                         width="56" height="56" alt="<?php echo $this->htmlEscape($_video->getLabel()) ?>"/>
                </a>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php endif; ?>
    <?php if (count($_images)): ?>
    <div id="m-image-tab">
        <ul>
            <?php foreach ($_images as $_image): ?>
            <li>
                <a href="#" class="m-image-thumbnail" id="m-image-<?php echo $_image->getId() ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
                    <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>"
                        width="56" height="56" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
                </a>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php endif; ?>
</div>
<?php else: ?>
<div class="more-views">
    <h2><?php echo $this->__('More Views') ?></h2>
    <ul>
        <?php foreach ($this->getMedias($_visibleVideos, $_images) as $_media): ?>
        <li>
            <?php if ($_media['type'] == 'image'): ?>
            <?php $_image = $_media['data']; ?>
            <a href="#" class="m-image-thumbnail" id="m-image-<?php echo $_image->getId() ?>"
               title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
                <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>"
                     width="56" height="56" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
            </a>
            <?php else: ?>
            <?php $_video = $_media['data']; ?>
            <a href="#" class="m-video-thumbnail" id="m-video-<?php echo $_video->getId() ?>"
               title="<?php echo $this->htmlEscape($_video->getLabel()) ?>">
                <img src="<?php echo $this->helper('manapro_video')->getVideoImage($_video, 'thumbnail', 56) ?>"
                     width="56" height="56" alt="<?php echo $this->htmlEscape($_video->getLabel()) ?>"/>
            </a>
            <?php endif; ?>
        </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
<?php endif; ?>
