<?php
/**
 * @category    Mana
 * @package     ManaPro_Video
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $_images = $this->getGalleryImages();
    $_videos = $this->getVideos();
    $_visibleVideos = Mage::helper('manapro_video')->getVisibleVideos($_videos);
    $_start = Mage::app()->getRequest()->getParam('start');
    /* @var $core Mana_Core_Helper_Data */ $core = Mage::helper(strtolower('Mana_Core'));
    $_largeWidth = Mage::getStoreConfig('manapro_video/popup/large_width');
    $_largeHeight = Mage::getStoreConfig('manapro_video/popup/large_height');
    $_smallWidth = Mage::getStoreConfig('manapro_video/popup/small_width');
    $_smallHeight = Mage::getStoreConfig('manapro_video/popup/small_height');
    $_maxColumnCount = floor((960 - $_largeWidth) / $_smallWidth);
    if ($_maxColumnCount < 1) {
        $_maxColumnCount = 1;
    }
    for ($_columnCount = 1; $_columnCount <= $_maxColumnCount; $_columnCount++) {
        $_videoHeight = ceil(count($_visibleVideos) / $_columnCount) * $_smallHeight;
        $_imageHeight = ceil(count($_images) / $_columnCount) * $_smallHeight;
        if ($_largeHeight - 60 >= $_videoHeight + $_imageHeight) {
            break;
        }
    }
    if ($_columnCount > $_maxColumnCount) {
        $_columnCount = $_maxColumnCount;
    }
?>
<div>
<div class="m-content">
<div class="m-large-image" style="width: <?php echo $_largeWidth?>px; height: <?php echo $_largeHeight; ?>px;">
<?php foreach ($_visibleVideos as $_video): ?>
    <p class="product-image" <?php if($_start != 'm-video-' . $_video->getId()) : ?>style="display: none;"<?php endif;?>
       id="m-popup-video-<?php echo $_video->getId() ?>-large" >
        <?php echo $this->getVideoHtml($_video, array_merge(array(
            'width' => $_largeWidth,
            'height' => $_largeHeight,
            'border' => 0
        ), $_start != 'm-video-' . $_video->getId() ? array() : array(
            //'autostart' => false,
        ))) ?>
    </p>
<?php endforeach; ?>
<?php foreach ($_images as $_image): ?>
    <p class="product-image" <?php if ($_start != 'm-image-' . $_image->getId()) : ?>style="display: none;"<?php endif;?>
       id="m-popup-image-<?php echo $_image->getId() ?>-large" >
        <?php
            $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image', $_image->getFile())->resize($_largeWidth, $_largeHeight).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
            echo $_helper->productAttribute($_product, $_img, 'image');
        ?>
    </p>
<?php endforeach; ?>
</div>
<div class="m-small-images" style="height: <?php echo $_largeHeight; ?>px;">
    <?php if (count($_visibleVideos)): ?>
    <div id="m-video-tab">
        <h2><?php echo $this->__('Videos') ?></h2>
        <ul style="width: <?php echo $_smallWidth * $_columnCount; ?>px;" >
            <?php foreach ($_visibleVideos as $_video): ?>
            <li>
                <a href="#" class="m-popup-video-thumbnail" id="m-popup-video-<?php echo $_video->getId() ?>"
                   title="<?php echo $this->htmlEscape($_video->getLabel()) ?>">
                    <img src="<?php echo $this->helper('manapro_video')->getVideoImage($_video, 'thumbnail', $_smallWidth, $_smallHeight) ?>"
                         width="<?php echo $_smallWidth?>" height="<?php echo $_smallHeight?>"
                         alt="<?php echo $this->htmlEscape($_video->getLabel()) ?>"/>
                </a>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php endif; ?>
    <?php if (count($_images)): ?>
    <div id="m-image-tab">
        <h2><?php echo $this->__('Images') ?></h2>
        <ul style="width: <?php echo $_smallWidth * $_columnCount; ?>px;">
            <?php foreach ($_images as $_image): ?>
            <li>
                <a href="#" class="m-popup-image-thumbnail" id="m-popup-image-<?php echo $_image->getId() ?>"
                   title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
                    <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_smallWidth, $_smallHeight); ?>"
                         width="<?php echo $_smallWidth?>" height="<?php echo $_smallHeight?>"
                         alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
                </a>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php endif; ?>
</div>
</div>
<div class="m-buttons">
    <button type="button" title="<?php echo $this->__('Previous') ?>" class="button m-btn-previous">
        <span><span><?php echo $this->__('Previous') ?></span></span>
    </button>
    <button type="button" title="<?php echo $this->__('Next') ?>" class="button m-btn-next">
        <span><span><?php echo $this->__('Next') ?></span></span>
    </button>
    <button type="button" title="<?php echo $this->__('Close') ?>" class="button m-btn-close">
        <span><span><?php echo $this->__('Close') ?></span></span>
    </button>

</div>
</div>