<?php
/**
 * @category    Mana
 * @package     ManaSlider_Tabbed
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */

/* @var $this ManaSlider_Tabbed_Block_ProductSlider */
/* @var $_products Mage_Catalog_Model_Resource_Eav_Mysql4_Product_Collection */
$_products = $this->getData('data_source');
$_sql = $_products->getSelect()->__toString();
?>
<div class="widget-products m-product-slider mb-<?php echo $this->jsHelper()->getClientSideBlockName($this->getNameInLayout()) ?>"
    data-m-block="ManaSlider/Tabbed/ProductSlider"
    data-ids="<?php echo $this->jsonHelper()->encodeAttribute($_products->getAllIds()) ?>"
    data-effect-duration="<?php echo $this->getData('effect_duration')?>"
    data-rotation-duration="<?php echo $this->getData('rotation_duration') ?>"
    data-url="<?php echo $this->urlTemplateHelper()->encodeAttribute(Mage::getUrl('mana/tabbedSlider/products')) ?>"
    data-xml="<?php echo base64_encode($this->getData('xml')) ?>"
    data-width="<?php echo $this->getData('image_width') ?>"
    data-slide-count="<?php echo $this->getData('slide_count') ?>">
    <a title="Previous" href="#" class="m-navigation-prev"></a>
    <a title="Next" href="#" class="m-navigation-next"></a>
    <ul class="products-grid">
    <?php echo $this->getChildHtml('product_list') ?>
    </ul>
</div>
