<?php
/**
 * @category    Mana
 * @package     ManaSlider_Tabbed
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */

/* @var $this ManaSlider_Tabbed_Block_ProductList */
/* @var $_products Mage_Catalog_Model_Resource_Eav_Mysql4_Product_Collection */
$_products = $this->getData('data_source');
$_helper = $this->helper('catalog/output');
?>
<?php $i = $this->getData('starting_from_product');
$img_width = $this->getData('image_width');
$img_height = $this->getData('image_height');
$is_visible_name = $this->getData('is_visible_name');
$is_visible_rating = $this->getData('is_visible_rating');
$is_visible_price = $this->getData('is_visible_price');
$is_visible_description = $this->getData('is_visible_description');
$is_visible_read_more = $this->getData('is_visible_read_more');
$is_visible_add_to_cart = $this->getData('is_visible_add_to_cart');
$is_visible_out_of_stock = $this->getData('is_visible_out_of_stock');
$is_visible_add_to_wishlist = $this->getData('is_visible_add_to_wishlist');
$is_visible_add_to_compare = $this->getData('is_visible_add_to_compare');

foreach ($_products->getItems() as $_product): $i++; ?>
    <li class="item item-<?php echo $i - 1; ?>" style="width: <?php echo $img_width ?>px;">
        <?php echo Mage::helper('manaproduct_tag')->beforeImage($this, $_product) ?>
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img
                src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($img_width, $img_height) ?>" width="<?php echo $img_width ?>" height="<?php echo $$img_height ?>"
                alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>"/></a>
        <?php echo Mage::helper('manaproduct_tag')->afterImage($this, $_product) ?>
        <?php if ($is_visible_name): ?>
            <h3 class="product-name">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)">
                <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
        <?php endif ?>
        <?php if ($is_visible_rating): ?>
            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
        <?php endif ?>
        <?php if ($is_visible_description): ?>
            <?php echo $_helper->productAttribute($_product,
                mb_substr($_product->getShortDescription(), 0, 100), 'short_description') ?>
        <?php endif ?>
        <?php if ($is_visible_read_more): ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>"
               class="link-learn"><?php echo $this->__('Learn More') ?></a>
        <?php endif ?>
        <?php if ($is_visible_price): ?>
            <?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
        <?php endif ?>
        <div class="actions">
            <?php if ($_product->isSaleable()): ?>
                <?php if ($is_visible_add_to_cart): ?>
                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                    <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                <?php endif ?>
            <?php else: ?>
                <?php if ($is_visible_out_of_stock): ?>
                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
            <?php endif; ?>
            <ul class="add-to-links">
                <?php if ($this->helper('wishlist')->isAllow() && $is_visible_add_to_wishlist): ?>
                    <li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                <?php endif; ?>
                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product) && $is_visible_add_to_compare): ?>
                    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                <?php endif; ?>
            </ul>
        </div>
    </li>
<?php endforeach; ?>

