<?php
/**
 * @category    Mana
 * @package     ManaSlider_Tabbed
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */

/* @var $this ManaSlider_Tabbed_Block_ProductSlider */
/* @var $_products Mage_Catalog_Model_Resource_Eav_Mysql4_Product_Collection */
$_products = $this->getDataSource();
$_sql = $_products->getSelect()->__toString();
?>
<div class="widget-products m-product-slider mb-<?php echo $this->jsHelper()->getClientSideBlockName($this->getNameInLayout()) ?>"
    data-m-block="ManaSlider/Tabbed/ProductSlider" data-ids="<?php echo $this->jsonHelper()->encodeAttribute($_products->getAllIds()) ?>"
    data-effect-duration="<?php echo $this->getData('effect_duration')?>">
    <a href="#" class="previous">Previous</a>
    <a href="#" class="next">Next</a>
<ul class="products-grid">
<?php $i = 0;
foreach ($_products->getItems() as $_product): $i++; ?>
    <li class="item item-<?php echo $i - 1; ?>">
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img
                src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(85) ?>" width="85" height="85"
                alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>"/></a>

        <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper(
                    'catalog/output'
                )->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
        <?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
        <div class="actions">
            <?php if ($_product->isSaleable()): ?>
                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                    <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
            <?php else: ?>
                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
            <ul class="add-to-links">
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                <?php endif; ?>
                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                <?php endif; ?>
            </ul>
        </div>
    </li>
<?php endforeach; ?>
</ul>
</div>
