<?php
/**
 * @category    Mana
 * @package     ManaSlider_Tabbed
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */

/* @var $this ManaSlider_Tabbed_Block_Slider */
/* @var $_tab Mage_Core_Block_Template */
$_title = $this->getData('title');
$_count = count($this->getChildGroup('tabs'));
?>
<div class="widget <?php echo $this->getData('css_class') ?>">
    <?php if ($_title): ?>
        <div class="widget-title">
            <h2><?php echo $this->__($_title) ?></h2>
        </div>
    <?php endif ?>
    <?php if ($_count > 1) : ?>
    <div class="m-tabbed-slider mb-<?php echo $this->jsHelper()->getClientSideBlockName($this->getNameInLayout()) ?>"
        data-m-block="ManaSlider/Tabbed/Slider">
        <ul class="m-tabs">
            <?php foreach ($this->getChildGroup('tabs') as $_tab) : ?>
                <li><a href="#m-<?php echo $_tab->getData('tab_id') ?>" title="<?php echo $this->escapeHtml($_tab->getData('title')) ?>">
                    <?php echo $_tab->getData('label') ?>
                </a></li>
            <?php endforeach;?>
        </ul>
        <ul class="m-tab-content">
            <?php foreach ($this->getChildGroup('tabs') as $_tab) : ?>
                <li id="m-<?php echo $_tab->getData('tab_id') ?>">
                    <?php echo $_tab->toHtml() ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php else: ?>
        <?php foreach ($this->getChildGroup('tabs') as $_tab) : ?>
            <?php echo $_tab->toHtml() ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>