<?php 
/**
 * @category    Mana
 * @package     ManaPro_Featured
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */

/* @var $this ManaPro_Featured_Block_List */
$_helper = $this->helper('catalog/output');
?>
<?php if (count($this->getItems())) : ?>
<?php if ($_shadowCss = $this->getDecorationCssClasses('shadow')) : ?>
<div class="m-shadow-container">
<?php endif ?>
<div class="m-featured <?php if ($_shadowCss) : ?>m-shadow <?php echo $_shadowCss ?><?php endif ?>">
    <?php foreach (array('top_left', 'top', 'top_right', 'right', 'bottom_right', 'bottom', 'bottom_left', 'left') as $_position) : ?>
        <?php if ($_decorationCssClasses = $this->getDecorationCssClasses($_position)) : ?>
        <div class="m-tag <?php echo $_decorationCssClasses ?>"></div>
        <?php endif;?>
    <?php endforeach; ?>

    <?php echo Mage::helper('mana_core')->getChildGroupHtml($this, 'top') ?>
    <div class="m-carousel">
    <ol class="products-list <?php echo $this->getCss() ?>">
    	<?php $_iterator = 0; foreach ($this->getItems() as $_product) :  ?>
            <li class="item<?php if (++$_iterator == count($this->getItems())): ?> last<?php endif; ?>">
                <?php // Product Image ?>
                <a href="<?php echo $_product->getProductUrl() ?>"
                   title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                   class="product-image"><img
                        src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>"
                        width="135" height="135"
                        alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/></a>
                <?php // Product description ?>
                <div class="product-shop">
                    <div class="f-fix">
                        <?php if (Mage::getStoreConfig($this->getConfigSource().'_carousel_fields/name')) : ?>
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                                    title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>
                        </h2>
                        <?php endif; ?>

                        <?php if (Mage::getStoreConfig($this->getConfigSource() . '_carousel_fields/rating')) : ?>
                        <?php if ($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
                        <?php endif; ?>
                        <?php endif; ?>

                        <?php if (Mage::getStoreConfig($this->getConfigSource() . '_carousel_fields/price')) : ?>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                        <?php endif; ?>

                        <?php if (Mage::getStoreConfig($this->getConfigSource() . '_carousel_fields/cart')) : ?>
                        <?php if ($_product->isSaleable()): ?>
                        <p>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart"
                                    onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        </p>
                        <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <?php endif; ?>

                        <div class="desc std">
                            <?php if (Mage::getStoreConfig($this->getConfigSource() . '_carousel_fields/description')) : ?>
                            <?php if ($_description = $_helper->productAttribute($_product, $_product->getMFeaturedDescription(), 'm_featured_description')) : ?>
                                <?php echo $_description ?>
                            <?php else : ?>
                                <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                            <?php endif; ?>
                            <?php endif; ?>
                            <a href="<?php echo $_product->getProductUrl() ?>"
                               title="<?php echo $_productNameStripped ?>"
                               class="link-learn"><?php echo $this->__('Learn More') ?></a>
                        </div>

                        <?php if (Mage::getStoreConfig($this->getConfigSource() . '_carousel_fields/links')) : ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                                   class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>"
                                                                    class="link-compare"><?php echo $this->__('Add to Compare') ?></a>
                            </li>
                            <?php endif; ?>
                        </ul>
                        <?php endif; ?>
                    </div>
                </div>
            </li>
    	<?php endforeach; ?>
    </ol>
    </div>
    <?php echo Mage::helper('mana_core')->getChildGroupHtml($this, 'bottom') ?>
    <?php echo Mage::helper('mana_core')->getChildGroupHtml($this, 'floating') ?>
</div>
<?php if ($_shadowCss) : ?>
</div>
<?php endif ?>
<?php endif; ?>
<script type="text/javascript">(function ($) { $(document).trigger('m-featured-carousel-reset', [<?php echo $this->getConfigJson() ?>]); })(jQuery);</script>
