<?php
/**
 * @category    Mana
 * @package     Mana_Admin
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="m-color-helper" class="m-helper">
	<div class="use-default">
        <input type="checkbox" id="m-color-helper-checkbox" class="m-default" />
        <label for="m-color-helper-checkbox" class="normal"><?php echo $this->__('Use Default Value') ?></label>
	</div>
	<div class="m-color-picker">
        <div class="mc-palette">
        </div>
        <div class="mc-gray">
        </div>
        <ul class="mc-predefined">
            <li class="mcp-0"></li>
            <li class="mcp-1"></li>
            <li class="mcp-2"></li>
            <li class="mcp-3"></li>
            <li class="mcp-4"></li>
            <li class="mcp-5"></li>
            <li class="mcp-6"></li>
            <li class="mcp-7"></li>
            <li class="mcp-8"></li>
            <li class="mcp-9"></li>
        </ul>
        <ul class="mc-footer">
            <li class="mcf-manual"><input size="8" /></li>
            <li class="mcf-transparent" ></li>
        </ul>
	</div>
</div>