<?php
/**
 * @category    Mana
 * @package     Mana_Admin
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="m-column-helper" class="m-helper">
	<div class="use-default">
        <input type="checkbox" id="m-column-helper-checkbox" class="m-default" />
        <label for="m-column-helper-checkbox" class="normal"><?php echo $this->__('Use Default Value') ?></label>
	</div>
</div>