<?php
/**
 * @category    Mana
 * @package     Mana_Admin
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="m-image-helper" class="m-helper">
	<div class="use-default">
        <input type="checkbox" id="m-image-helper-checkbox" class="m-default" />
        <label for="m-image-helper-checkbox" class="normal"><?php echo $this->__('Use Default Value') ?></label>
	</div>
	<ul class="mi-buttons">
        <li class="scalable add m-button">
            <span><?php echo $this->__('Add') ?></span>
        </li>
        <li class="scalable change m-button">
            <span><?php echo $this->__('Change') ?></span>
        </li>
        <li class="scalable delete m-button">
            <span><?php echo $this->__('Remove') ?></span>
        </li>
    </ul>
</div>