<?php
/**
 * @category    Mana
 * @package     Mana_Checkout
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/**
 * @author Mana Team
 *
 */
 /* @var $this Mana_Checkout_Block_Order_Review */
?>
<div class="m-order-review">
    <div class="order-review" id="checkout-review-load">
        <?php echo $this->getChildHtml('info') ?>
    </div>
    <?php echo $this->getChildHtml('message') ?>
    <?php echo $this->getChildHtml('terms') ?>
    <div id="checkout-review-submit">
        <div class="buttons-set" id="review-buttons-container">
            <button type="submit" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout"
                    ><span><span><?php echo $this->__('Place Order') ?></span></span></button>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/mana_core/m-wait.gif') ?>"
                 alt="<?php echo $this->__('Submitting order information...') ?>"
                 title="<?php echo $this->__('Submitting order information...') ?>"
                 class="v-middle"/> <p><?php echo $this->__('Submitting order information...') ?></p>
        </span>
        <span class="please-wait" id="review-updating" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/mana_core/m-wait.gif') ?>"
                 alt="<?php echo $this->__('Verifying...') ?>"
                 title="<?php echo $this->__('Verifying...') ?>"
                 class="v-middle"/> <p><?php echo $this->__('Verifying...') ?></p>
        </span>
        </div>
    </div>
</div>
