<?php
/**
 * @category    Mana
 * @package     Mana_Checkout
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/**
 * @author Mana Team
 *
 */
 /* @var $this Mana_Checkout_Block_Payment_Cvv */
?>
<div class="cvv-description-text tool-tip" id="payment-tool-tip" style="display:none;">
    <div>
        <div class="btn-close"><a href="#" class="m-close-popup"
                                  title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
        <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>"
                                           alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>"
                                           title="<?php echo $this->__('Card Verification Number Visual Reference') ?>"/>
        </div>
    </div>
</div>
