<?php
/**
 * @category    Mana
 * @package     ManaPro_FilterPositioning
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php if($this->canShowBlock()): ?>
<div class="block block-layered-nav m-top">
    <div class="block-content">
        <?php echo $this->getStateHtml() ?>
        <?php if (Mage::helper('mana_core')->isMageVersionEqualOrGreater('1.7') && $this->getLayer()->getState()->getFilters()) : ?>
        <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
        <?php if($this->canShowOptions()): ?>
            <div id="narrow-by-list">
              <?php if (Mage::getStoreConfigFlag('mana_filters/positioning/shop_by_title')) : ?>
                <div class="block-subtitle">
                        <strong><span><?php echo $this->__('Shop By') ?></span></strong>
                </div>                
                <div class="hidden"></div>
              <?php endif; ?>


                <?php $_filters = $this->getFilters() ?>
                  <?php foreach ($_filters as $_filter): ?>
                  <?php if($_filter->getItemsCount()): ?>
              <dl <?php if ($_height = Mage::getStoreConfig('mana_filters/positioning_horizontal/height')) : ?> style="min-height: <?php echo $_height?>px;"<?php endif; ?>
                <?php if($_filter->getFilterOptions()) : ?>class="m-<?php echo $_filter->getFilterOptions()->getDisplay() ?>"<?php endif; ?>>
                      <dt class="m-ln">
                          <?php Mage::helper('mana_filters')->renderHtml($this, 'horizontal_name_before', array('filter' => $_filter)); ?>
                          <?php echo $this->__($_filter->getName()) ?>
                      </dt>
                      <dd class="m-ln"><?php echo $_filter->getHtml() ?></dd>
              </dl>
                  <?php endif; ?>
                  <?php endforeach; ?>
                  
            </div>
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
