<?php
/**
 * @category    Mana
 * @package     Mana_AttributePage
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
if ($this instanceof Mage_Catalog_Block_Navigation) {
    /* @var $this Mage_Catalog_Block_Navigation */
    $_menu = $this->renderCategoriesMenuHtml(0, 'level-top');
}
else {
    /* @var $this Mage_Page_Block_Html_Topmenu */
    $_menu = $this->getHtml('level-top');
}
/* @var $_block Mana_AttributePage_Block_Navigation */
$_block = Mage::getSingleton('core/layout')->getBlockSingleton('mana_attributepage/navigation');
$_attributeMenu = $_block->getHtml();
?>
<?php if($_menu || $_attributeMenu): ?>
<div class="nav-container">
    <div class="nav-border-left"></div>
    <ul id="nav">
        <li <?php if(Mage::helper('mana_theme')->isHomePage() ) : ?>class="active"<?php endif; ?> data="<?php echo Mage::helper('mana_theme')->getFullActionName() ?>">
          <a href="<?php echo $this->getUrl() ?>"><?php echo $this->__('Home') ?></a>
        </li>
        <?php echo $_menu ?>
        <?php echo $_attributeMenu ?>
        <li><a href="<?php echo $this->getUrl() ?>blog/">Blog & Documentation</a></li>
    </ul>
    <div class="nav-border-right"></div>
</div>
<?php endif ?>
