<?php
/**
 * @category    Mana
 * @package     ManaProduct_Review
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
?>
<?php
/* @var $this ManaProduct_Review_Block_Block */
?>
<h2 id="review-list"><?php echo $this->__('Customer Reviews') ?></h2>
<div class="box-collateral box-reviews m-reviews" id="customer-reviews">
<?php echo $this->getChildHtml() ?>
</div>
