<?php
/**
 * @category    Mana
 * @package     ManaProduct_Review
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/* @var $this ManaProduct_Review_Block_List */
?>
<?php 
    $_items = $this->getReviewsCollection()->getItems();
    $_currentCol = 2;
    $_columnCount = 2;
?>
<?php if (count($_items)):?>

    <?php foreach ($_items as $_review):?>
        <?php if ($_currentCol == 1) : ?>
            </div>
            <div class=col<?php echo $_columnCount?>-set>
        <?php endif;?>

        <div class="col-<?php echo $_currentCol++; ?>">
            <h3><?php echo $this->htmlEscape($_review->getTitle()) ?></h3>
            <p class="review-author"">
                <?php echo $this->__('<span>%s</span>', $this->htmlEscape($_review->getNickname())) ?> 
                <small class="date"><?php echo $this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt()), 'long') ?></small>
            </p>

            <?php $_votes = $_review->getRatingVotes(); ?>
            <?php foreach ($_votes as $_vote): ?>
                <div class="rating-box">
                    <div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
                </div>
            <?php endforeach; ?>

            <div class="review-content">
                <?php echo nl2br($this->htmlEscape($_review->getDetail())) ?>
            </div>
        </div>
        
        <?php if($_currentCol > $_columnCount) $_currentCol = 1; ?>
    <?php endforeach; ?>


<?php endif;?>

<?php if ($_currentCol != 1) : ?>
    <?php while($_currentCol <= $_columnCount) : ?>
        <div class="col-<?php echo $_currentCol++; ?>"></div>
    <?php endwhile; ?>
<?php endif;?>
</div>

<?php if (count($_items)):?>
    <?php echo $this->getChildHtml('toolbar') ?>
<?php endif;?>
