<?php
/**
 * @category    Mana
 * @package     ManaProduct_Review
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
?>
<?php
/* @var $this ManaProduct_Review_Block_Random */
?>
<?php if ($this->getReviews()) : ?>
<div class="widget widget-random-review">
    <?php if ($this->getTitle()) :?>
    <div class="widget-title">
        <h2><?php echo $this->getTitle() ?></h2>
    </div>
    <?php endif; ?>
    <div class="widget-content">
        <?php foreach ($this->getReviews() as $_review): ?>
        <?php /* @var $_review Mage_Review_Model_Review */ ?>
        <?php $text = $this->getCharacterCount() ? mb_substr($_review->getDetail(), 0, $this->getCharacterCount()) : $_review->getDetail(); ?>
        <?php $_product = $this->getProduct($_review); ?>
        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
        <div class="block block-random-review">
            <div class="block-title"><strong>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name'); ?></a> -
                <span><?php echo $_review->getTitle() ?></span>
            </strong></div>
            <div class="block-content">
                <div class="product">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(50) ?>" width="50" height="50" alt="<?php echo $_productNameStripped; ?>" /></a>
                    <div class="product-details">
                        <div class="std">
                            <?php echo $text ?>
                            <?php if ($text != $_review->getDetail()): ?>
                            ... <a class="read-more" href="<?php echo $this->getReadMoreUrl($_review) ?>" title="<?php echo $this->__('Read more') ?>"><?php echo $this->__('Read more') ?></a>
                            <?php endif; ?>
                        </div>
                        <div class="written-by"><?php echo $_review->getNickname() ?></div>
                    </div>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>