<?php
/**
 * @category    Mana
 * @package     ManaProduct_Review
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
?>
<?php if ($this->getReviewsCount()): ?>
<div class="ratings">
    <?php if ($this->getRatingSummary()): ?>
    <div class="rating-box">
        <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
    </div>
    <?php endif;?>
    <span class="amount"><a href="<?php echo $this->getReviewsUrl() ?>#review-list"
                            class="m-open-review-list"><?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?></a></span>
</div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
<p class="no-rating"><a href="<?php echo $this->getReviewsUrl() ?>#review-form"
                        class="m-open-review-form"><?php echo $this->__('Be the first to review this product') ?></a>
</p>
<?php endif; ?>
