<?php
/**
 * @category    Mana
 * @package     Mana_Admin
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * This template displays grid page's content 
 */
/* @var $this Mana_Admin_Block_V2_Container */
?>
<div class="content-header">
<table cellspacing="0">
    <tr>
		<td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
        <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
    </tr>
</table>
</div>
<div>
    <?php if ($this->getIsTabContainer()) : ?>
        <div id="tab-content"></div>
    <?php endif; ?>
    <?php foreach ($this->getChildGroup('content', 'getChildHtml') as $alias => $html): ?>
	<?php echo $html; ?>
<?php endforeach; ?>
</div>
