<?php
/**
 * @category    Mana
 * @package     Mana_InfiniteScrolling
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
?>
<ul class="hidden">
    <li class="infinite-scrolling-list-loader">
        <img src="<?php echo $this->getSkinUrl('images/mana_infinitescrolling/loader.gif') ?>"
             alt="<?php echo $this->__('Loading, please wait ...') ?>"
             title="<?php echo $this->__('Loading, please wait ...') ?>"
             class="v-middle"/>
        <?php echo $this->__('Loading, please wait ...') ?>
    </li>
</ul>
<p class="infinite-scrolling-grid-loader">
    <img src="<?php echo $this->getSkinUrl('images/mana_infinitescrolling/loader.gif') ?>"
         alt="<?php echo $this->__('Loading, please wait ...') ?>"
         title="<?php echo $this->__('Loading, please wait ...') ?>"
         class="v-middle"/>
    <?php echo $this->__('Loading, please wait ...') ?>
</p>
