<?php
/**
 * @category    Mana
 * @package     Mana_InfiniteScrolling
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
?>
<?php
/* @var $this Mage_Catalog_Block_Product_List_Toolbar */
?>
<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar">
    <div class="pager">
        <p class="amount">
            <?php if($this->getLastPageNum()>1): ?>
                <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            <?php else: ?>
                <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
            <?php endif; ?>
        </p>

    <?php if( $this->isExpanded() ): ?>
        <div class="sort-by">
            <label><?php echo $this->__('Sort By') ?></label>
            <select onchange="setLocation(this.value)">
            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                    <?php echo $this->__($_order) ?>
                </option>
            <?php endforeach; ?>
            </select>
            <?php if($this->getCurrentDirection() == 'desc'): ?>
                <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/i_desc_arrow.gif') ?>" alt="<?php echo $this->__('Set Ascending Direction') ?>" class="v-middle" /></a>
            <?php else: ?>
                <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/i_asc_arrow.gif') ?>" alt="<?php echo $this->__('Set Descending Direction') ?>" class="v-middle" /></a>
            <?php endif; ?>
        </div>

        <?php if ($this->isEnabledViewSwitcher()): ?>
            <p class="view-mode">
                <?php $_modes = $this->getModes(); ?>
                <?php if ($_modes && count($_modes) > 1): ?>
                <label><?php echo $this->__('View as') ?>:</label>
                <?php foreach ($this->getModes() as $_code => $_label): ?>
                    <?php if ($this->isModeActive($_code)): ?>
                        <strong title="<?php echo $_label ?>"
                                class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>&nbsp;
                        <?php else: ?>
                        <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>"
                           class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>&nbsp;
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </p>
            <?php endif; ?>

        <?php endif; ?>
    </div>
</div>
<?php endif ?>
