<?php
/**
 * @category    Mana
 * @package     Mana_Checkout
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/**
 * @author Mana Team
 *
 */
 /* @var $this Mana_Checkout_Block_Order_Info */
?>
<div class="m-order-info">
    <div id="checkout-review-table-wrapper">
        <table class="data-table" id="checkout-review-table">
            <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
            <col/>
            <col width="1"/>
            <col width="1"/>
            <col width="1"/>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <col width="1"/>
            <col width="1"/>
            <?php endif; ?>
            <thead>
            <tr>
                <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product Name') ?></th>
                <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Price') ?></th>
                <th rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
                <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Subtotal') ?></th>
            </tr>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <tr>
                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
            </tr>
                <?php endif; ?>
            </thead>
            <?php echo $this->getChildHtml('totals'); ?>
            <tbody>
            <?php foreach ($this->getItems() as $_item): ?>
                <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        decorateTable('checkout-review-table');
        truncateOptions();
        //]]>
    </script>
</div>
