<?php 
/**
 * @category    Mana
 * @package     ManaPro_Guestbook
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/* @var $this Mage_Core_Block_Template */
?>
<?php if (Mage::getStoreConfigFlag('manapro_guestbook/name/is_enabled')) : ?>
<?php $_required = Mage::getStoreConfigFlag('manapro_guestbook/name/is_required'); ?>
    <label for="name" <?php if ($_required) : ?>class="required"<?php endif; ?>>
        <?php if ($_required) : ?><em>*</em><?php endif; ?><?php echo $this->__('Name') ?>
    </label>
    <div class="input-box">
        <input name="name" id="name" title="<?php echo $this->__('Name') ?>"
            value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>"
            class="input-text <?php if ($_required) : ?>required-entry <?php endif; ?>" type="text" />
    </div>
<?php endif; ?>