<?php 
/**
 * @category    Mana
 * @package     ManaPro_Guestbook
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/* @var $this Mage_Core_Block_Template */
?>
<?php if (Mage::getStoreConfigFlag('manapro_guestbook/url/is_enabled')) : ?>
<?php $_required = Mage::getStoreConfigFlag('manapro_guestbook/url/is_required'); ?>
    <label for="url" <?php if ($_required) : ?>class="required"<?php endif; ?>>
        <?php if ($_required) : ?><em>*</em><?php endif; ?><?php echo $this->__('Website') ?>
    </label>
    <div class="input-box">
        <input name="url" id="url" title="<?php echo $this->__('Website') ?>"
            class="input-text <?php if ($_required) : ?>required-entry <?php endif; ?>" type="text" />
    </div>
<?php endif; ?>