<?php

/**
 * @var $this Local_Manadev_Block_Domain_Registration
 */
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo Mage::helper('local_manadev')->__('Product Registration') ?></h1>
</div>
<form action="<?php echo $this->getFormAction(); ?>" id="domainForm" class="m-form" method="post">
    <input type="hidden" name="branch" id="branch">
    <div>
        <strong>Product:</strong> <?php echo $this->getProductName(); ?>
    </div>
    <div>
        <strong>Order #:</strong> <?php echo $this->getOrderNo(); ?>
    </div>
    <div>
        <h4>Please enter your Store Admin Panel URL:</h4>
        <div class="input-box">
            <input class="input-text" id="admin_panel_url" type="text" name="domain" value="<?php echo $this->getDomain(); ?>"/>
        </div>
        <blockquote class="m-lightgrey">
            <p class="note">You may only use this purchased product and get support for it on this store.</p>
            <p class="note">The entered URL will be validated to make sure that it exists.</p>
            <p class="note">Admin panel URL is requested instead of base URL because it is possible to use multiple domains for a magento installation, but there is only one admin panel URL.</p>
        </blockquote>
    </div>

    <div>
        <h4>In case you don't have a configured store yet, please provide your store information</h4>
        <textarea rows="4" cols="64" name="m_store_info"><?php echo $this->getStoreInfo() ?></textarea>
        <blockquote class="m-lightgrey">
            <p class="note">For example, "The extension will be used for selling XYZ products of ABC company. I cannot provide my store admin panel URL right now because ..."</p>
        </blockquote>
    </div>

    <div class="buttons-set">
        <?php if(Mage::getSingleton('customer/session')->getData('m_start_download')): ?>
            <?php if($labels = $this->getProductBranchLabels()):?>
                <button class="button m-download-menu-button"><span><span>Register and Download</span></span></button>
                <ul class="m-download-menu">
                    <?php foreach ($labels as $branch => $label): ?>
                        <li>
                            <a title="<?php echo $label ?>"
                                data-branch="<?php echo $branch ?>"
                                href="#">
                                <span><span><?php echo $label ?></span></span>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php else: ?>
                <button type="submit" class="button"><span><span>Register and Download</span></span></button>
            <?php endif; ?>
        <?php else: ?>
            <button type="submit" class="button"><span><span>Save Changes</span></span></button>
        <?php endif; ?>
    </div>
</form>