<?php
/**
 * @category    Mana
 * @package     Mana_Admin
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$_element = $this->getElement()
?>
<?php if ($_element->getFieldsetContainerId()): ?>
<div id="<?php echo $_element->getFieldsetContainerId(); ?>" <?php if ($_element->getFieldsetContainerClass()) : ?>class="<?php echo $_element->getFieldsetContainerClass() ?>"<?php endif; ?>>
<?php endif; ?>
<?php if ($_element->getLegend()): ?>
<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $_element->getLegend() ?></h4>
    <div class="form-buttons"><?php echo $_element->getHeaderBar() ?></div>
</div>
<?php endif; ?>
<?php if (!$_element->getNoContainer()): ?>
    <div class="fieldset <?php echo $_element->getClass() ?>" id="<?php echo $_element->getHtmlId() ?>">
<?php endif; ?>
    <div <?php //class="hor-scroll"?>>
        <?php if ($_element->getComment()): ?>
            <p class="comment"><?php echo $this->escapeHtml($_element->getComment()) ?></p>
        <?php endif; ?>
        <?php if ($_element->hasHtmlContent()): ?>
            <?php echo $_element->getHtmlContent(); ?>
        <?php else: ?>
        <table cellspacing="0" class="<?php echo $_element->hasTableClass() ? $_element->getTableClass() : 'form-list'?>">
            <tbody>
                <?php echo $_element->getChildrenHtml(); ?>
            </tbody>
        </table>
        <?php endif; ?>
    </div>
    <?php echo $_element->getSubFieldsetHtml() ?>
<?php if (!$_element->getNoContainer()): ?>
    </div>
<?php endif; ?>
<?php if ($_element->getFieldsetContainerId()): ?>
</div>
<?php endif; ?>
