<?php 
$current_cat = Mage::getSingleton('blog/cat');
$cats = $this->getCategories(); 
?>
<div class="menu-categories links add-to-links">
    <ul>
    <?php foreach ($cats as $cat): ?>
    		<li <?php echo $cat->getCatId() == $current_cat->getCatId() ? 'class="current"' : '' ?>><a href="<?php echo $cat->getAddress(); ?>" ><?php echo $cat->getTitle();?></a></li>
    <?php endforeach; ?>
	</ul>
</div>	
