<?php if (Mage::getStoreConfig(AW_Blog_Helper_Config::XML_TAGCLOUD_SIZE) && $this->getCollection()->count()): ?>
<div class="menu-tags">
<ul class="tagcloud links add-to-links">
	<?php foreach($this->getCollection() as $tag):?>
        <?php if ($tag->getTag()) : ?>
		      <li><a class="tag-count-<?php echo $this->getTagWeight($tag)?>" href="<?php echo $this->getTagHref($tag)?>"><?php echo $tag->getTag()?></a></li>
        <?php endif;?>
	<?php endforeach;?>  
</ul>
</div>
<?php endif;?>
