<script type="text/javascript"> 
//<![CDATA[
LightboxOptions = Object.extend({
    fileLoadingImage:        '<?php echo $this->getSkinUrl('images/loading.gif') ?>',     
    fileBottomNavCloseImage: '<?php echo $this->getSkinUrl('images/closelabel.gif') ?>',

    overlayOpacity: 0.8,   // controls transparency of shadow overlay

    animate: true,         // toggles resizing animations
    resizeSpeed: 7,        // controls the speed of the image resizing animations (1=slowest and 10=fastest)

    borderSize: 10,         //if you adjust the padding in the CSS, you will need to update this variable

	// When grouping images this is used to write: Image # of #.
	// Change it for non-english localization
	labelImage: "<?php echo $this->__('Image') ?>",
	labelOf: "<?php echo $this->__('of') ?>"
}, window.LightboxOptions || {});
//]]>
</script> 