<?php
/**
 * @category    Mana
 * @package     Local_Manadev
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/* @var $this Local_Manadev_Block_Thankyou */
?>
<p>Thank you for yout interest in <strong><?php echo $this->getProduct()->getName() ?></strong>! Download 
will start in few seconds. In case it does not start automatically, you can also 
<a href="<?php echo $this->getFileUrl() ?>">download it here</a>. </p>