<?php
/**
 * @category    Mana
 * @package     Mana_Checkout
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/**
 * @author Mana Team
 *
 */
 /* @var $this Mana_Checkout_Block_Billing_Address */
?>
<div class="m-billing-address">
    <div class="section-title">
        <?php if(Mage::getSingleton('customer/session')->isLoggedIn()):?>
        <h2><?php echo $this->__('Billing Address') ?></h2>
        <?php else: ?>
        <h2><?php echo $this->__('Register or') ?> <button type="button" class="login-link button" title="Login"><span><span>Login</span></span></button></h2>
        <script type="text/javascript">
            Mana.require(['jquery', 'singleton:Mana/Core/Layout'], function($, layout) {
                $(document).on('click', '.login-link', function() {
                    layout.showPopup({
                        content: $('.login-form-text'),
                        popup: {
                            'class': 'login-form--popup-container',
                            'blockName': 'Mana/Checkout/LoginPopup'
                        },
                        noHeightAdjustment: true
                    });
                    return false;
                });
            });
        </script>
        <?php endif; ?>
    </div>
    <fieldset class="form-list">
        <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>"
               id="billing:address_id"/>
        <div class="billing-account-form">
            <ul>
                <li class="fields">
                    <div class="field name-firstname">
                        <label for="billing:firstname" class="required"><em>*</em><?php echo $this->__('Your Name') ?></label>
                        <div class="input-box">
                            <input type="text" id="billing:firstname" name="billing[firstname]" value="<?php echo $this->htmlEscape($this->getAddress()->getFirstname()) ?>" 
                                title="<?php echo $this->__('First Name') ?>" class="input-text required-entry"
                                placeholder="<?php echo $this->__('Your Name') ?>" />
                        </div>
                    </div>
                </li>
                <li class="fields" id="register-customer-password">
                    <div class="field billing-email">
                        <label for="billing:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?>
                        </label>

                        <div class="input-box">
                            <input type="text" name="billing[email]" id="billing:email"
                                   value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>"
                                   title="<?php echo $this->__('Email Address') ?>"
                                   class="input-text validate-email required-entry"
                                   placeholder="<?php echo $this->__('Email Address') ?>"/>
                        </div>
                    </div>
                    <?php if(!Mage::getSingleton('customer/session')->isLoggedIn()) : ?>
                    <div class="field">
                        <label for="billing:customer_password"
                               class="required"><em>*</em><?php echo $this->__('Password') ?></label>

                        <div class="input-box">
                            <input type="password" name="billing[customer_password]" id="billing:customer_password"
                                   title="<?php echo $this->__('Password') ?>"
                                   class="input-text required-entry validate-password"
                                   placeholder="<?php echo $this->__('Password') ?>"/>
                        </div>
                    </div>
                    <div class="field">
                        <label for="billing:confirm_password"
                               class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>

                        <div class="input-box">
                            <input type="password" name="billing[confirm_password]"
                                   title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password"
                                   class="input-text required-entry validate-cpassword"
                                   placeholder="<?php echo $this->__('Confirm Password') ?>"/>
                        </div>
                    </div>
                    <?php endif ?>
                    <div class="field billing-country <?php echo $this->getAddress()->hasCountryId() ? '' : 'updatable' ?>">
                        <label for="billing:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?>
                        </label>

                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect('billing') ?>
                        </div>
                    </div>
                    <!--<div class="field billing-state">
                        <label for="billing:region_id" class="required"><em>*</em><?php echo $this->__('State') ?>
                        </label>

                        <div class="input-box">
                            <select id="billing:region_id" name="billing[region_id]"
                                    title="<?php echo $this->__('State') ?>" class="validate-select"
                                    style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                                //<![CDATA[
                                $('billing:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
                                //]]>
                            </script>
                            <input type="text" id="billing:region" name="billing[region]"
                                   value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"
                                   title="<?php echo $this->__('State/Province') ?>" class="input-text"
                                   style="display:none;"
                                   />
                        </div>
                    </div>-->
                </li>
            </ul>
        </div>
        <div class="billing-company-form">
            <h3 class="m-collapseable" <?php if(!$this->getAddress()->getCompany()): ?>data-initially="collapsed"<?php endif ?>><?php echo $this->__('I Need Invoice') ?></h3>
            <ul>
                <li class="fields">
                    <div class="field">
                        <label for="billing:company"><?php echo $this->__('Company Name') ?>
                        </label>

                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Company Name') ?>" name="billing[company]"
                                   id="billing:company"
                                   value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>"
                                   class="input-text validate-zip-international"
                                   placeholder="<?php echo $this->__('Company Name') ?>"/>
                        </div>
                    </div>
                    <div class="field">
                        <label for="billing:company_code"><?php echo $this->__('Company Code') ?>
                        </label>

                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Company Code') ?>"
                                   name="billing[m_company_code]"
                                   id="billing:company_code"
                                   value="<?php echo $this->htmlEscape($this->getAddress()->getMCompanyCode()) ?>"
                                   class="input-text validate-zip-international"
                                   placeholder="<?php echo $this->__('Company Code') ?>"/>
                        </div>
                    </div>
                    <div class="field billing-vat">
                        <label for="billing:company_vat"><?php echo $this->__('VAT Number') ?>
                            <span class="vat-status"></span>
                        </label>

                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('VAT Number') ?>" name="billing[m_vat_number]"
                                   id="billing:company_vat"
                                   value="<?php echo $this->htmlEscape($this->getAddress()->getMVatNumber()) ?>"
                                   class="input-text validate-zip-international"
                                   placeholder="<?php echo $this->__('VAT Number') ?>"/>
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="billing:street1"><?php echo $this->__('Address') ?></label>

                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Street Address') ?>"
                                   name="billing[street][]"
                                   id="billing:street1"
                                   value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>"
                                   class="input-text"
                                   placeholder="<?php echo $this->__('Street Address') ?>"/>
                        </div>
                    </div>
                    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <div class="field">
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>"
                                   name="billing[street][]" id="billing:street<?php echo $_i?>"
                                   value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i)) ?>"
                                   class="input-text"
                                   placeholder="<?php echo $this->__('Street Address %s', $_i) ?>"/>
                        </div>
                    </div>
                    <?php endfor ?>
                    <div class="field">
                        <label for="billing:city"><?php echo $this->__('City') ?></label>

                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]"
                                   value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>"
                                   class="input-text" id="billing:city"
                                   placeholder="<?php echo $this->__('City') ?>"/>
                        </div>
                    </div>
                    <div class="field">
                        <label for="billing:zip"><?php echo $this->__('Zip') ?>
                        </label>

                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Zip') ?>" name="billing[postcode]"
                                   id="billing:zip"
                                   value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>"
                                   class="input-text"
                                   placeholder="<?php echo $this->__('Zip') ?>"/>
                        </div>
                    </div>
                </li>
                <li class="no-display"><input type="hidden" name="billing[region]" value="1"/></li>
                <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1"/></li>
                <li class="no-display"><input type="hidden" name="billing[use_for_shipping]" value="1"/></li>
                <li class="no-display"><input type="hidden" name="billing[create_account]" value="1"/></li>
            </ul>
        </div>
    </fieldset>
</div>
