<?php
/**
 * @category    Mana
 * @package     Mana_Page
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/* @var $this Mana_Page_Block_Widget */
    /* @var $_theme Mana_Theme_Helper_Data */
    $_theme = Mage::helper('mana_theme');
?>
<?php if (($_products = $this->getProductCollection()->load()) && $_products->getSize()): ?>
<div class="widget widget-<?php echo $this->getType() ?>">
    <div class="block block-list <?php echo Mage::helper('mana_theme')->getCssClass($this, 'manapage_'.$this->getType()) ?>">
        <div class="block-title">
            <strong><span><?php echo $this->getBlockTitle() ?></span></strong>
        </div>
        <div class="block-content">
            <?php $suffix = $this->getNameInLayout(); ?>
            <ol class="mini-products-images-list" id="widget-<?php echo $this->getType() ?>-<?php echo $suffix; ?>">
            <?php foreach ($_products as $_product): ?>
                <li class="item">
                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"  style="height: <?php echo $_theme->getHeight(76) ?>px;"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(76, $_theme->getHeight(76)) ?>" width="76" height="<?php echo $_theme->getHeight(76) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                </li>
            <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('widget-<?php echo $this->getType() ?>-<?php echo $suffix; ?>', 'none-recursive')</script>
        </div>
    </div>
</div>
<?php endif; ?>
