<?php
/**
 * @category    Mana
 * @package     Mana_Page
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/* @var $this Mana_Page_Block_Widget */
    /* @var $_theme Mana_Theme_Helper_Data */
    $_theme = Mage::helper('mana_theme');
    $_helper = $this->helper('catalog/output');
?>
<?php if (($_products = $this->getProductCollection()->load()) && $_products->getSize()): ?>
<div class="widget widget-<?php echo $this->getType() ?>">
    <div class="widget-title">
        <h2><?php echo $this->getBlockTitle() ?></h2>
    </div>
    <div class="widget-products">
        <?php $i=0; foreach ($_products as $_product): ?>
            <?php if ($i++%2==0): ?>
            <ol class="products-list <?php echo $i == 1 ? 'first' : ''; ?>">
            <?php endif ?>
            <li class="item<?php echo ($i == count($_products))?' last':''; ?> <?php echo $i % 2 ? 'odd' : 'even' ?> <?php echo $_theme->getListItemClass($this, $_product) ?>">
                <?php echo Mage::helper('manaproduct_tag')->beforeImage($this, $_product) ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image" style="height: <?php echo $_theme->getHeight(150) ?>px;"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(150, $_theme->getHeight(150)) ?>" width="150" height="<?php echo $_theme->getHeight(150) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                <?php echo Mage::helper('manaproduct_tag')->afterImage($this, $_product) ?>
                <div class="product-shop">
                    <div class="f-fix">
                        <?php if ($_theme->isVisibleInProductList($this, 'name')): ?>
                            <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                        <?php endif; ?>
                        <?php if ($_theme->isVisibleInProductList($this, 'rating')): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php endif; ?>
                        <?php if ($_theme->isVisibleInProductList($this, 'description') || $_theme->isVisibleInProductList($this, 'read_more')): ?>
                        <div class="desc std">
                            <?php if ($_theme->isVisibleInProductList($this, 'description')): ?>
                                <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                            <?php endif; ?>
                            <?php if ($_theme->isVisibleInProductList($this, 'read_more')): ?>
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                            <?php endif; ?>
                        </div>
                        <?php endif; ?>
                      </div>
                    </div>
                <div class="actions-block">
                        <?php if ($_theme->isVisibleInProductList($this, 'price')): ?>
                            <?php echo $this->getPriceHtml($_product, true, '-widget-' . $this->getType() . '-list') ?>
                        <?php endif; ?>
                        <?php if ($_theme->isVisibleInProductList($this, 'wishlist') || $_theme->isVisibleInProductList($this, 'compare')): ?>
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow() && $_theme->isVisibleInProductList($this, 'wishlist')) : ?>
                                    <?php if (!($_wishlistItem = $_theme->inWishlist($_product))): ?>
                                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php else: ?>
                                        <li><a href="<?php echo $this->helper('wishlist')->getRemoveUrl($_wishlistItem) ?>" class="link-wishlist" title="<?php echo $this->__('Remove from Wishlist') ?>"><?php echo $this->__('In Wishlist') ?></a></li>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if(($_compareUrl=$this->getAddToCompareUrl($_product)) && $_theme->isVisibleInProductList($this, 'compare')): ?>
                                    <?php if (!($_compareItem = $_theme->inCompare($_product))): ?>
                                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                                    <?php else: ?>
                                        <li><span class="separator">|</span> <a href="<?php echo $this->helper('catalog/product_compare')->getRemoveUrl($_compareItem) ?>" class="link-compare" title="<?php echo $this->__('Remove from Compare') ?>"><?php echo $this->__('In Compare') ?></a></li>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </ul>
                        <?php endif; ?>

                        <?php if($_product->isSaleable()): ?>
                            <?php if ($_theme->isVisibleInProductList($this, 'cart')): ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php if ($_theme->isVisibleInProductList($this, 'out_of_stock')): ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
            </li>
            <?php if ($i%2==0 || $i==count($_products)): ?>
            </ol>
            <?php endif ?>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
