<?php
/**
 * @category    Mana
 * @package     Mana_Content
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */

/* @var $this Mana_Content_Block_Book_Content */
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="std">
    <h1><?php echo $this->getTitle(); ?></h1>
    <div class="mana_content">
        <?php echo $this->parseContent(); ?>
    </div>
</div>