<?php
/**
 * @category    Mana
 * @package     Local_Manadev
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/* @var $this Local_Manadev_Block_Download_Button */
?>
<button type="button" title="<?php echo $this->__('Download') ?>" 
	class="button btn-cart btn-download for-product-<?php echo $this->getProduct()->getId() ?>">
	<span><span><?php echo $this->__('Download') ?></span></span>
</button>
		        