<?php 
/**
 * @category    Mana
 * @package     ManaPro_FilterCheckboxes
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/** 
 * Template for showing options for filter as a HTML list 
 * @author Mana Team
 */
/* @var $this Mana_Content_Block_Filter_RelatedProduct */

?>
<?php
if($this->getItems()->getSize() > 0):
?>
<div class="block m-container">
    <div class="block-title"><?php $this->helper('mana_content')->__('Related Product Filter'); ?></div>
    <div class="block-content">
        <ol class="m-content-css-checkboxes">
            <?php foreach ($this->getItems() as $_item): ?>
            <li>
                <a
                    data-m-product-id="<?php echo $_item->getId(); ?>">
                        <?php echo $this->escapeHtml($_item->getName()) ?>
                </a>
            </li>
            <?php endforeach ?>
        </ol>
    </div>
</div>
<?php endif ?>