<?php
/** @var $this Mana_Content_Block_Filter_Search */
?>
<div class="block m-container">
    <div class="block-title"><?php echo $this->contentHelper()->__('Search'); ?></div>
    <div class="block-content">
        <form>
            <input id="searchCms" type="text" placeholder="<?php echo $this->contentHelper()->__("Search tree here...") ?>" autocomplete="off"/>
            <button type="submit" title="<?php echo $this->contentHelper()->__('Search'); ?>" class="button search-button"><span><span><?php echo $this->contentHelper()->__('Search'); ?></span></span></button>
            <a href="" style="display: none"></a>
        </form>
    </div>
</div>