<?php
if($this->getTags()->getSize ()> 0):
?>
<div class="block block-tags">
    <div class="block-title">
        <strong><span><?php echo $this->__('CMS Tags'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul class="tags-list">
            <?php foreach ($this->getTags() as $_tag): ?>
                <li><a data-m-tag-id="<?php echo $_tag->getData('page_tag_id'); ?>" style="font-size:<?php echo $_tag->getRatio()*70+75 ?>%;"><?php echo $this->htmlEscape($_tag->getName()) ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif ?>