<?php
/**
 * @category    Mana
 * @package     ManaPro_ProductFaces
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
?>
<?php
/**
 * @var $this Mage_Core_Block_Template
 */
?>
<?php echo $this->getChildHtml('m_representing_messages_wrapper') ?>
<?php echo $this->getChildHtml('catalog.product.edit.tab.m_representing_header') ?>
<?php echo $this->getChildHtml('catalog.product.edit.tab.m_representing') ?>
<?php echo $this->getChildHtml('m_representing_grid_serializer') ?>
