<?php
/**
 * @category    Mana
 * @package     Mana_InfiniteScrolling
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
?>
<?php
/* @var $this Mana_InfiniteScrolling_Block_Progress */
?>
<span class="please-wait" style="display:none;">
    <img src="<?php echo $this->getSkinUrl('images/mana_infinitescrolling/ajax-loader.gif') ?>"
         alt="<?php echo $this->__('Loading...') ?>"
         title="<?php echo $this->__('Loading...') ?>"
         class="v-middle"/> <?php echo $this->__('Loading...') ?>
</span>
