
<?php

/**
 * @var $this Local_Manadev_Block_Support_TicketForm
 */
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo Mage::helper('local_manadev')->__('Open Support Ticket') ?></h1>
</div>
<form action="<?php echo $this->getFormAction(); ?>" id="ticketForm" class="m-form" method="post" enctype="multipart/form-data">
    <div class="fieldset">
        <ul class="form-list">
            <li class="fields">
                <h2 class="legend"><?php echo Mage::helper('local_manadev')->__('Product Information') ?></h2>
                <div class="field">
                    <label for="productName">Product</label>
                    <div id="productName" class="input-box"><?php echo $this->getProductName(); ?></div>
                </div>
                <div class="field">
                    <label for="orderNumber">Order #</label>
                    <div id="orderNumber" class="input-box"><?php echo $this->getOrderNo(); ?></div>
                </div>
            </li>

            <li class="wide">
                <label for="issue_details"><strong><?php echo Mage::helper('local_manadev')->__('Issue Details') ?>:</strong></label>
                <div class="input-box">
                    <textarea rows="10" cols="100" name="issue_details"><?php echo $this->getIssueDetails()?></textarea>
                    <br/>
                    <em>Please provide the following information on the Issue Details:</em>
                    <p class="note">Direct link to page having the issue and specify exact steps on how to reproduce the issue.</p>
                    <p class="note">If site is protected by .htaccess or other means, please provide corresponding credentials.</p>
                    <p class="note">If you think that we need detailed examination on the server, please provide Magento Admin Panel and SFTP credentials.</p>
                    <!--        <p class="note">Please provide direct link to page having the issue and describe exact steps to reproduce the issue.</p>-->
                </div>
            </li>

            <li>
                <label for="screenshot_1"><?php echo Mage::helper('contacts')->__('Screenshot 1') ?></label>
                <div class="input-box">
                    <input name="screenshot_1" id="screenshot_1" class="input-text" type="file" accept="image/png, image/jpeg"/>
                    <br/>
                    <p class="note">Accepts JPEG and PNG files only.</p>
                </div>
                <label for="screenshot_2"><?php echo Mage::helper('contacts')->__('Screenshot 2') ?></label>
                <div class="input-box">
                    <input name="screenshot_2" id="screenshot_2" class="input-text" type="file" accept="image/png, image/jpeg"/>
                </div>
                <label for="screenshot_3"><?php echo Mage::helper('contacts')->__('Screenshot 3') ?></label>
                <div class="input-box">
                    <input name="screenshot_3" id="screenshot_3" class="input-text" type="file" accept="image/png, image/jpeg"/>
                </div>
            </li>
        </ul>
    </div>

    <div class="buttons-set">
        <button type="submit" title="<?php echo Mage::helper('local_manadev')->__('Submit Support Ticket') ?>" class="button"><span><span><?php echo Mage::helper('local_manadev')->__('Submit Support Ticket') ?></span></span></button>
    </div>
</form>