<?php
/**
 * @category    Mana
 * @package     Local_Manadev
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/* @var $this Local_Manadev_Block_Review */
?>
<a title="<?php echo $this->__('See What Other People Think') ?>" 
	class="button btn-cart" href="<?php echo $this->getReviewsUrl() ?>">
	<span><span><?php echo $this->__('Reviews') ?></span></span>
</a>
