<?php
/**
 * @category    Mana
 * @package     Mana_AttributePage
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/* @var $this Mana_AttributePage_Block_Navigation */
/* @var $_page Mana_AttributePage_Model_OptionPage_Store */
/* @var $_collection Mana_AttributePage_Resource_OptionPage_Store_Collection */
$i = 0;
$_collection = $this->getData('collection');
?>
<?php foreach($_collection as $_page) : ++$i; ?>
    <?php
        $_siblingClass = $i == 1 ? 'first' : ($i == count($_collection->getItems()) ? 'last' : '');
        $_activeClass = $this->isOptionPageActive($_page) ? 'active' : '';
    ?>
    <li class="level-1 nav-option-<?php echo $_page->getId()?> <?php echo $_activeClass ?> <?php echo $_siblingClass ?>">
        <a href="<?php echo $_page->getUrl() ?>">
            <span><?php echo $this->escapeHtml($_page->getData('title')) ?></span>
        </a>
    </li>
<?php endforeach; ?>