<?php 
/**
 * @category    Mana
 * @package     ManaPro_Slider
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */

/* @var $this ManaPro_Slider_Block_CmsBlock */
/* @var $_slider ManaPro_Slider_Block_Slider */
$_slider = $this->getParentBlock();
?>
<?php if ($this->getCmsBlock()): ?>
    <?php echo $this->getHtml() ?>
<?php endif ?>