<?php
/**
 * @category    Mana
 * @package     Mana_Checkout
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/**
 * @author Mana Team
 *
 */
 /* @var $this Mana_Checkout_Block_Login */
?>
<div class="login-form-text" style="display:none;">
<div>
    <div class="btn-close"><a href="#" class="m-close-popup"
                              title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a>
    </div>
    <div class="page-title">
        <h2><?php echo $this->__('Login') ?></h2>

        <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
    </div>
    <div>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <ul class="form-list">
            <li>
                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>

                <div class="input-box">
                    <input type="text" name="login[username]"
                           value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email"
                           class="input-text required-entry validate-email"
                           title="<?php echo $this->__('Email Address') ?>"/>
                </div>
            </li>
            <li>
                <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>

                <div class="input-box">
                    <input type="password" name="login[password]"
                           class="input-text required-entry validate-password" id="pass"
                           title="<?php echo $this->__('Password') ?>"/>
                </div>
            </li>
        </ul>
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>

        <div class="buttons-set">
            <a href="<?php echo $this->getForgotPasswordUrl() ?>"
               class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
            <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2">
                <span><span><?php echo $this->__('Login') ?></span></span></button>
        </div>
    </form>
    <script type="text/javascript">
        var dataForm = new VarienForm('login-form', true);
    </script>
</div>
</div>
