<?php
/**
 * @category    Mana
 * @package     Mana_Checkout
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/**
 * @author Mana Team
 *
 */
 /* @var $this Mana_Checkout_Block_Container */
?>
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<div class="m-checkout">
    <div class="page-title">
        <h1><?php echo $this->__('Simple & Secure Checkout') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form id="checkout-form" method="post" action="<?php //echo $this->getUrl('checkout/ajax/save') ?>">
    <ul class="m-columns m-checkout-columns">
        <li class="column1 first">
            <?php echo $this->getChildHtml('billing_address') ?>
        </li>
        <li class="column2 last">
            <?php echo $this->getChildHtml('order_review') ?>
        </li>
    </ul>
    </form>
    <?php if (!$this->isCustomerLoggedIn()) : ?>
    <?php echo $this->getChildHtml('login') ?>
    <?php endif ?>
    <?php echo $this->getChildHtml('payment_cvv') ?>
</div>
