<?php
/**
 * @category    Mana
 * @package     ManaProduct_Review
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
?>
<?php if ($this->getReviewsCount()): ?>
<div class="ratings">
    <?php if ($this->getRatingSummary()): ?>
    <div class="rating-box">
        <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
    </div>
    <?php endif;?>
    <p class="rating-links">
        <a href="<?php echo $this->getReviewsUrl() ?>#review-list"
           class="m-open-review-list"><?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?></a>
        <span class="separator">|</span>
        <a href="<?php echo $this->getReviewsUrl() ?>#review-form"
           class="m-open-review-form"><?php echo $this->__('Add Your Review') ?></a>
    </p>
</div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
<p class="no-rating"><a href="<?php echo $this->getReviewsUrl() ?>#review-form"
                        class="m-open-review-form"><?php echo $this->__('Be the first to review') ?></a>
</p>
<?php endif; ?>
