<?php
/**
 * @category    Mana
 * @package     ManaProduct_Review
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */

 /* @var ManaProduct_Review_Block_Helper $this */
?>
<?php if ($this->getReviewsCount()): ?>
<div class="ratings">
    <?php if ($this->getRatingSummary()): ?>
    <div class="rating-box">
        <div itemprop="aggregateRating" itemscope itemtype="https://schema.org/AggregateRating"
            class="rating" style="width:<?php echo $this->getRatingSummary() ?>%">
            <meta itemprop="ratingValue" content="<?php echo round($this->getRatingSummary() / 100 * 5, 1) ?>" />
            <meta itemprop="reviewCount" content="<?php echo $this->getReviewsCount() ?>" />
            <meta itemprop="ratingCount" content="<?php echo $this->getReviewsCount() ?>" />
            <meta itemprop="bestRating" content="5" />
            <meta itemprop="worstRating" content="1" />
        </div>
    </div>
    <?php endif;?>
    <p class="rating-links">
        <a href="<?php echo $this->getReviewsUrl() ?>#review-list"
           class="m-open-review-list"><?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?></a>
        <span class="separator">|</span>
        <a href="<?php echo $this->getReviewsUrl() ?>#review-form"
           class="m-open-review-form"><?php echo $this->__('Add Your Review') ?></a>
    </p>
</div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
<p class="no-rating"><a href="<?php echo $this->getReviewsUrl() ?>#review-form"
                        class="m-open-review-form"><?php echo $this->__('Be the first to review') ?></a>
</p>
<?php endif; ?>
