<?php 
/**
 * @category    Mana
 * @package     ManaPro_ProductPlusProduct
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */

?>
<?php if (Mage::getStoreConfigFlag('mana_productlists/m_productplusproduct/is_enabled') && count($this->getCollection()->getItems())) : ?>
<div class="m-bought-together">
	<?php $_size = Mage::getStoreConfig('mana_productlists/m_productplusproduct/image_size'); ?>
	<?php $_productBlock = Mage::getSingleton('core/layout')->getBlock('product.info'); ?>
	<?php $_product = Mage::registry('current_product'); ?>
    <h2><?php echo Mage::getStoreConfig('mana_productlists/m_productplusproduct/title') ?></h2>
  <div>
    <form id="m-bought-together-form" method="post" action="<?php echo $this->addToCartUrl() ?>">
    <input type="hidden" name="product_info" id="m-bought-together-product-info" />
    <div class="m-bought-together-visuals">
    <ul class="m-bought-together-products">
    	<?php $_separatorNeeded = false; foreach ($this->getItems() as $_link) :  ?>
    		<?php if ($_separatorNeeded) : ?>
    		<li class="m-separator" style="height: <?php echo $_size ?>px;">&nbsp;</li>
    		<?php else : $_separatorNeeded = true; ?>
    		<?php endif; ?>
    		<li class="m-product" id="m-bought-together-product-<?php echo $_link->getId() ?>">
    			<?php if ($_link->getId() == $_product->getId()) : ?>
	                <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize($_size) ?>" width="<?php echo $_size ?>" height="<?php echo $_size ?>" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" />
				<?php else : ?>
	                <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize($_size) ?>" width="<?php echo $_size ?>" height="<?php echo $_size ?>" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a>
				<?php endif; ?>
    		</li>
    	<?php endforeach; ?>
      <li class="m-bought-together-summary">
      	<div>
  	    	<span class="m-bought-together-subtotal-label"><?php echo $this->__('Price') ?>:</span> 
  		    <span class="regular-price m-bought-together-subtotal"><span><?php echo Mage::app()->getStore()->formatPrice($_link->getFinalPrice()) ?></span></span>
  	    </div>
  		<div class="add-to-box m-bought-together-add-to-box">
  		    <div class="add-to-cart">
  		        <?php if(Mage::getStoreConfigFlag('mana_productlists/m_productplusproduct/allow_qty')): ?>
  		        <label for="m-bought-together-qty"><?php echo $this->__('Qty:') ?></label>
  		        <input type="text" name="qty" id="m-bought-together-qty" maxlength="12" value="<?php echo $this->getMinimalQty($_product) ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
  		        <?php endif; ?>
  		        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
  		    </div>
  			<ul class="add-to-links">
  			<?php if ($this->helper('wishlist')->isAllow()) : ?>
  			    <li><a href="<?php echo $this->addToWishlistUrl() ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
  			<?php endif; ?>
  			<?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) ): ?>
  			    <li><span class="separator">|</span> <a href="<?php echo $this->addToCompareUrl() ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
  			<?php endif; ?>
  			</ul>
          </div>
      </li>
    </ul>
    <ul class="m-bought-together-options">
    	<?php foreach ($this->getItems() as $_link) : ?>
    	<li>
			<input type="checkbox" name="product[]" id="m-bought-together-option-<?php echo $_link->getId() ?>" value="<?php echo $_link->getId() ?>" checked="checked" />
			<?php if ($_link->getId() == $_product->getId()) : ?>
                <label for="m-bought-together-option-<?php echo $_link->getId() ?>">
	                <?php echo $this->htmlEscape($_link->getName()) ?>
	                <span class="regular-price"><span class="price"><?php echo Mage::app()->getStore()->formatPrice($_link->getFinalPrice()) ?></span></span>
                </label>
			<?php else : ?>
                <label for="m-bought-together-option-<?php echo $_link->getId() ?>">
	                <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a>
	                <span class="regular-price"><span class="price"><?php echo Mage::app()->getStore()->formatPrice($_link->getFinalPrice()) ?></span></span>
                </label>
			<?php endif; ?>
    	</li>
    	<?php endforeach; ?>
    </ul>
    </div>
    </form>
  </div> 
</div>
<?php endif; ?>
