<?php
/** 
 * @category    Mana
 * @package     Mana_AttributePage
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/* @var $this Mana_AttributePage_Block_Attribute_View */
$_attributePage = $this->getAttributePage();
$_filesHelper = $this->filesHelper();
$_escapedTitle = $this->escapeHtml($_attributePage->getData('title'));
$_description = $_attributePage->getData('description');
$_description = Mage::helper('cms')->getBlockTemplateProcessor()->filter($_description);
$_descriptionBottom = $_attributePage->getData('description_bottom');
$_descriptionBottom = Mage::helper('cms')->getBlockTemplateProcessor()->filter($_descriptionBottom);
$_productListDescription = Mage::helper('cms')->getBlockTemplateProcessor()->filter($_attributePage->getData('product_list_description'));
?>
<div class="page-title category-title m-attribute-page-title">
    <h1><?php echo $_escapedTitle ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if (($_imgUrl = $_attributePage->getData('image')) && $_filesHelper->shouldRenderImage($_imgUrl)): ?>
    <p class="category-image m-attribute-page-image">
        <img alt="<?php echo $_escapedTitle ?>" title="<?php echo $_escapedTitle ?>"
            <?php echo $_filesHelper->renderImageAttributes($_imgUrl, $_attributePage->getData('image_width'), $_attributePage->getData('image_height')) ?> />
    </p>
<?php endif; ?>
<div class="category-description m-attribute-page-description top std">
    <?php echo $_description ?>
</div>
<?php if ($_attributePage->getData('')) ?>
<?php echo $this->getChildHtml('option_featured') ?>
<?php echo $this->getChildHtml('option_alpha') ?>
<?php echo $this->getChildHtml('option_list') ?>

<?php if($_attributePage->getData('show_product_list')): ?>
    <?php if($_productListDescription): ?>
        <div class="category-description m-attribute-page-product-list-description std">
            <?php echo $_productListDescription ?>
        </div>
    <?php endif; ?>
    <?php echo $this->getChildHtml('product_list') ?>
<?php endif; ?>

<div class="category-description m-attribute-page-description bottom std">
    <?php echo $_descriptionBottom ?>
</div>
